import { DataFilter, Dialog, MasterPanel, Message, h } from '../../src/index.js';
import { dataFilterStateToFilters, zeyosForm, zeyosTable } from '../../src/zeyos/index.js';
// The dedicated ZeyOS client library (npm: @zeyos/client), bundled for the zero-build site.
import { createZeyosClient } from '../vendor/zeyos-client.esm.js';
import { installMockZeyosApi } from '../mock-zeyos-api.js';

const TABLE_FIELDS = ['transactionnum', 'account', 'date', 'duedate', 'netamount', 'status'];
const FORM_FIELDS = [...TABLE_FIELDS, 'currency'];
const FIELD_LABELS = {
  transactionnum: 'Invoice number',
  account: 'Customer',
  date: 'Issue date',
  duedate: 'Due date',
  netamount: 'Net amount',
  status: 'Status',
  currency: 'Currency'
};
const STATUS_OPTIONS = [
  { value: 0, label: 'Draft' },
  { value: 1, label: 'Booked' },
  { value: 16, label: 'Invoiced' },
  { value: 20, label: 'Paid' },
  { value: 21, label: 'Overpaid' }
];

export default {
  title: 'ZeyOS invoices',
  group: 'Applications',
  blurb: 'The reference ZeyOS integration: the table, the filters, and the dialog editor are all '
    + 'generated by zx-zeyos from the live schema an injected @zeyos/client exposes.',

  /**
   * Mounts a complete invoices screen driven by the ZeyOS OpenAPI client.
   * @param {HTMLElement} container Documentation stage.
   * @returns {void}
   */
  mount(container) {
    // No backend or credentials are needed here: the mock answers the OpenAPI endpoints with
    // Unix-second timestamps and real server-side query handling. Point `platform` at a live
    // instance and drop this call to run the same code against ZeyOS.
    installMockZeyosApi();

    // The binding receives an existing client; it never imports or bundles @zeyos/client itself.
    // (@zeyos/client instances are frozen, so the generators normalize list responses with their
    // own built-in fallback rather than attaching anything to the client.)
    const client = createZeyosClient({
      platform: 'https://cloud.zeyos.com/demo/',
      auth: { mode: 'session', session: { enabled: true, credentials: 'include' } }
    });

    let activeDialog = null;
    let activeSearch = '';
    let activeFilters = {};

    const sourceStatus = h('span', { 'aria-live': 'polite' }, 'Waiting for zx-zeyos.');
    const sourceNote = h('p', { class: 'invoice-source' },
      h('span', {},
        h('strong', {}, 'zx-zeyos: '),
        'generates this data view from the injected client’s runtime schema.'),
      sourceStatus);

    const list = zeyosTable(client, 'transactions', {
      fields: TABLE_FIELDS,
      labels: FIELD_LABELS,
      pageSize: 25,
      sort: { id: 'date', dir: 'desc' },
      selectable: 'multi',
      height: 380,
      onRowClick: (row) => openEditor(row.ID)
    });

    const loadMore = h('button', {
      class: 'zx-btn',
      type: 'button',
      hidden: true,
      onclick: () => loadNextPage()
    }, 'Load more');
    const tableWrap = h('div', {
      class: 'invoice-table-wrap',
      'aria-busy': 'true'
    }, list.table, loadMore);

    const filter = new DataFilter(null, {
      data: [],
      clearLabel: 'Clear filters',
      filters: [
        {
          type: 'text',
          id: 'search',
          label: 'Find invoice',
          fields: ['transactionnum', 'account_label'],
          placeholder: 'Customer or invoice number'
        },
        {
          type: 'select',
          id: 'status',
          label: 'Status',
          field: 'status',
          emptyLabel: 'All statuses',
          options: STATUS_OPTIONS
        }
      ],
      onfilter: (event) => {
        activeSearch = String(event.detail.state.search ?? '');
        activeFilters = dataFilterStateToFilters(
          { status: event.detail.state.status },
          [{ id: 'status', field: 'status' }]
        );
        void loadInvoices('filters');
      }
    });

    const dataLayer = h('aside', { class: 'data-layer-note' },
      h('h2', {}, 'About the data layer'),
      h('p', {},
        'The table and form are schema-driven: ',
        h('code', {}, 'zx-zeyos'),
        ' generates them from the real ZeyOS ',
        h('code', {}, 'transactions'),
        ' and ',
        h('code', {}, 'accounts'),
        ' schemas exposed by the injected ',
        h('strong', {}, '@zeyos/client'),
        '. Typed metadata selects the date, amount, enum, and entity widgets automatically.'),
      h('p', {},
        'Queries use ',
        h('code', {}, 'filters'),
        ' (plural), Unix-second timestamps, and server-side sorting and paging — the table never '
        + 'sorts locally.'));

    const workspace = h('div', { class: 'invoice-workspace' },
      sourceNote, filter, tableWrap, dataLayer);

    const shell = new MasterPanel(null, {
      title: 'Invoices',
      module: 'billing',
      content: workspace,
      buttons: [
        { label: 'New invoice', icon: 'plus', kind: 'primary', onclick: () => openEditor(null) },
        { label: 'Refresh', icon: 'reload', onclick: () => loadInvoices('refresh') }
      ],
      footer: 'Schema-driven via zx-zeyos + @zeyos/client'
    });
    container.append(h('div', { class: 'layout-frame' }, shell.toElement()));

    list.table.on('datachange', () => {
      loadMore.hidden = !list.hasMore;
      sourceStatus.textContent = 'Showing ' + list.table.getData().length
        + (list.count == null ? ' transactions.' : ' of ' + list.count + ' transactions.');
    });
    list.table.on('sort', (event) => {
      sourceStatus.textContent = 'Server sorting by ' + event.detail.id + '…';
    });

    void loadInvoices('initial');

    /**
     * Reloads the first page for the active search and filters.
     * @param {string} reason Why the reload was triggered; shown in the status line.
     * @returns {Promise<void>}
     */
    async function loadInvoices(reason) {
      tableWrap.setAttribute('aria-busy', 'true');
      list.table.setLoading(true);
      sourceStatus.textContent = reason === 'filters'
        ? 'Applying server filters…'
        : 'client.api.listTransactions() · loading…';
      try {
        await list.load({ search: activeSearch, filters: activeFilters, page: 0 });
      } catch (error) {
        sourceStatus.textContent = 'Could not load transactions: ' + error.message;
      } finally {
        tableWrap.setAttribute('aria-busy', 'false');
        list.table.setLoading(false);
      }
    }

    /** Appends the next server page. @returns {Promise<void>} */
    async function loadNextPage() {
      loadMore.disabled = true;
      list.table.setLoading(true);
      try {
        await list.loadMore();
      } catch (error) {
        Message.error('Could not load more transactions: ' + error.message);
      } finally {
        loadMore.disabled = false;
        list.table.setLoading(false);
      }
    }

    /**
     * Opens the generated editor for an existing or a new invoice.
     * @param {number|null} id Transaction ID, or null to create one.
     * @returns {void}
     */
    function openEditor(id) {
      if (activeDialog?.isOpen()) return;
      const isEdit = id != null;
      const editor = zeyosForm(client, 'transactions', {
        fields: FORM_FIELDS,
        labels: FIELD_LABELS,
        title: 'Invoice details',
        columns: 2,
        ...(isEdit ? { id } : { value: newInvoiceValue() }),
        onSaved: async (record) => {
          sourceStatus.textContent = 'Saved ' + record.transactionnum + ' through zx-zeyos.';
          await loadInvoices('saved');
        }
      });
      const dialog = new Dialog(null, {
        title: isEdit ? 'Edit invoice' : 'New invoice',
        size: 'lg',
        content: editor.form,
        buttons: [
          { label: 'Cancel', action: 'cancel' },
          {
            label: 'Save invoice',
            kind: 'primary',
            autofocus: true,
            action: () => saveEditor(dialog, editor)
          }
        ]
      });
      activeDialog = dialog;
      dialog.once('close', () => {
        editor.destroy();
        dialog.destroy();
        if (activeDialog === dialog) activeDialog = null;
      });
      dialog.open();
      setDialogSaving(dialog, true);
      editor.ready.then(() => {
        if (dialog.isOpen()) setDialogSaving(dialog, false);
      }).catch((error) => {
        if (!dialog.isOpen()) return;
        sourceStatus.textContent = 'Could not load the invoice: ' + error.message;
        dialog.setButtons([{ label: 'Close', action: 'close', autofocus: true }]);
        setDialogSaving(dialog, false);
      });
    }

    /**
     * @param {Dialog} dialog Open dialog.
     * @param {{save: () => Promise<unknown>}} editor Generated form binding.
     * @returns {Promise<void>}
     */
    async function saveEditor(dialog, editor) {
      setDialogSaving(dialog, true);
      try {
        const saved = await editor.save();
        if (saved && dialog.isOpen()) dialog.close(saved);
      } catch (error) {
        sourceStatus.textContent = 'Could not save the invoice: ' + error.message;
      } finally {
        if (dialog.isOpen()) setDialogSaving(dialog, false);
      }
    }

    /** @param {Dialog} dialog @param {boolean} saving @returns {void} */
    function setDialogSaving(dialog, saving) {
      dialog.el.setAttribute('aria-busy', String(saving));
      dialog.el.querySelectorAll('[data-dialog-button]').forEach((control) => {
        control.disabled = saving;
      });
    }

    /** @returns {Record<string, unknown>} */
    function newInvoiceValue() {
      const today = Math.floor(Date.now() / 86_400_000) * 86_400;
      return {
        transactionnum: '',
        account: null,
        date: today,
        duedate: today + 30 * 86_400,
        netamount: null,
        status: 0,
        currency: 'EUR'
      };
    }
  }
};
